preserveTaxonomyNames: 'true'
baseurl: https://example.org/
languageCode: en-us
title: HUGO MyPortfolio Theme
theme: hugo-myportfolio-theme
markup:
  goldmark:
    renderer:
      unsafe: yes
params:
  custom_css: custom.css
  homepage:
    sections:
      - home
      - about
      - services
      - skills
      - projects
      - contact
  meta:
    author: <AUTHOR>
    description: <DESCRIPTION>
    favicon: favicon.ico
  navigation:
    brand: YOUR BRAND
    links:
      about: ABOUT
      contact: CONTACT
      projects:
        - label: PROFESSIONAL
          section: pro
        - label: PERSONAL
          section: perso
      services: SERVICES
      skills: SKILLS
  page404:
    background_image: 404.jpg
    button_text: BACK HOME
    text: OOPS, PAGE NOT FOUND!
  projects:
    categories:
      - pro
      - perso
    date_format: Jan-2006
    nb_columns: '3'
    nb_columns_small: '2'
    posts_order: date
    posts_order_reverse: yes
    sections_order: title
    sections_order_reverse: no
